### ISSUE TITLE
application.yml 내 Redis property 변경

### ISSUE THREAD

**Issue by dlask913** [team-archivist/archivist-backend#211]
### 🔍 상세 설명
- application.yml 내 아래 설정이 deprecated 되어 변경
```yml
  redis:
    host: 223.130.128.93
    port: 6379
    password: beside17
```

### ✔️ 할 일(TO DO) 체크리스트
- [x] 아래와 같이 변경
```yml
  data:
    redis:
      host: localhost
      port: 6379
      password: beside17
```

### 🚩 고려사항
- 운영에 Redis 올라가 있는 지 확인 부탁드립니다.
